travis:
  secure:
    BINSTAR_TOKEN: JLe+UnoZM2uifo3cQzAbMzWmCkwYbWRfXTGF6yyi4geFwY0t4SBFLQ7c54M0LY8u4PUhG8SY9AmOQLTAosONllJlrnGQjQgQPtJCE5ldg0PDzIY5BCyo7hjVqRbumBW2DKzlvj6O51tc5JpQC57MtlSpdsRuBQqoMaBoDpiigq6GQV1+52U16J4qaZv3wWXPZFX09PO68TddqhiaPBAuStURgOI6zlUYcsfBUZa1nlJRPAN1uOd6Ql0S86fO7+7lGwUWNLjonLeoCnxxFsdkC9OeX0r3e28IHZ7hz34qImyv2x7CAyR0ClD7CEp5a40IG28uX6bIVF8bL5w3IjPwYxGmsjboFPGX0VReP5FtIeIw9mCs1GC9sjhKLMOc9si+Y2n5s3/nzqzVKgp36GT4bkNUXR06e9G4yIuo6QbhCZuaBISWgJIjImCKQrnpG8DcorqfLOym2evxJEmM8zznzGmyFViR5+LoDL0DuW4JqltMbUNOCjyJJL8UeyjZ+L+1G57MenQ0lOszHxJTLqujhxHWjeMWFU3g/Y4iJ54ceH8J6A7zgFgiQk4qE7dT3qGuec+V5RPP5MbNH2x2404nlJRtwicITuc1RjSw6oneptFdg8oSwm6hmoTMU3ea3JHBR3iUAerpmYFo/W0mi8Aq14pUmUyoeiY5jGGloOY75pk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
