appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Q89tlOFTTQWOyS4Ei19oc3Ef3WejUgMHWzC2w5kZJRlDbssKHDHKK2DP8qXHKPOPvhcbxcVSr/Ue9Jozx5TJVEo28Ipk/XQ35i0+vVUobZF7yb73BJV8ms4Hw5sRO5HDR9Kxav/9OMLMKtZzz9OGjkiAPEJ3zuvIVDQzcw7/niB2Wz0t0aUuIi1l/eeSulP1e5l8TdDGEOE3ttEh5cErCoKsLi9dS4QT7r2O+72TZK0flDSJoYe5cnIfyysxABwZKHwFwDW/s2D+Drk5zzfAGU9NmroZWM0Z6+QwZUw4HL1KYozLTnAFjx7MV8YonAn1JEnVL+ZmaEeW33bmDBbyM3XEIxGIFgGRH2yGmeONx+HVw4AznEedpCgapRyBzy5JeqN/oEcsa2jMdpzeRdDCStlp4Xu6NeNMYOc3ONfhjCXyBiXEEwzSO5AVYYg3BmNI2JjgjxY1qHKMNVqgWGTlr4J4Bei+SfRNMMZSHTPt4GuEy20TuN7POKIKJ5lzTwFymbB4C4PMMmIg+rWmRgWh9TGU90JTYmSKj+W+Hp8+XCjqFnfhE4CKn/avG6svj+/OH+mdWjwfxqOakyGqAAfJZs4qDaq/XiGvApr1ADWa6zGO6yYClWveyDeZbRe18gUYWoTkiR1UlDFruVZqrU0A5okLFZeiLGwmrE9PMWsMvNk=}
