travis:
  secure:
    BINSTAR_TOKEN: GK82ocPZunEwqCPxnDoYUMIQ6d7K81XYYebBZl3P3zUtA8ha+xGcKBfElwaZZDVARAhoOSk8L64fx8Nn0bKYHFreTe55ICFa/XLeO/5OFx/vYz+Ivf3S36qHPpe4mklxAEVOLawRn4dm3GWaP9IbqBhAiR+vin2Yq+HJvxSEzrEUAVjvIv2CTgAJQywlwq+r2xhjALvnP/IPOfTeTBKwIDSANltH3pwtTW5sPvAqEulCj0hG4hZBzNgcPcMPfu8XLeCIH/ssuB3COB4UTLdpszFLoxIKmDqj4Mgk/TANYIH0TR08WPPsZ/IkYE62sX+ZwXiFN9fk9flPROWEyrSfydC1G5z52PED5lMFmdbzjUu9WZMguNjHxOat1++fcVZ95N9K0f+Tcnvl1ewRNND49COy7O6ltUvC1MzpkiNUjovtZXLrMFqm38Ew65VKhuv+bUxRXgCE45djExchKT+DhCIx2e4SCzJhJ/Fbo3zlKhxdiKHQYY2N+bmETTm7TLSGPSUXCSC8EM4jzbBhY0qt3lDWWaBWD7wZ6Fich4YdLEZAXsTYhafYl3i+eUANegbcGFkkKQN7gvFCj0nos+isljLCfSheQWDWsmzyoDWdwzFhM/vvMgsbX2Wjm18SbTnocgx5b1oDX7DL+hRGpJJjCRsOa2ElEUtVQTIVZjQEaao=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
